### ISSUE TITLE
problem: Invalid SSL cert being served for https://www.howlongistheline.org

### ISSUE THREAD

**Issue by jimkleine** [gazhayes/howlongistheline.org#52]
The domain (only) cert is being served, even when the www URL is accessed.  You should add www.howlongistheline.org to the LetsEncrypt cert as a Subject Alternate Name (SAN).

**Comment by gazhayes** [comment]
Thanks for the heads up, I'll get onto it.

**Comment by gazhayes** [comment]
@jimkleine this is now done (it's in production), can you verify (and close if so)?

**Comment by jimkleine** [comment]
solution: Add www to LetsEncrypt cert as Subject Alternate Name (SAN)

Tested and confirmed fixed.

**Comment by jimkleine** [comment]
GitHub hiccup: issue not closed on last comment?
