### ISSUE TITLE
suggestion: ability to mark stores as favorites

### ISSUE THREAD

**Issue by jeremysherriff** [gazhayes/howlongistheline.org#59]
Great work, thanks for being the person who did something useful with an idea!

I'd love the ability to mark a few stores as favorites. To continue with the concept of not using logins, the favourite information can be stored in a cookie.

You would then need a way of doing something with the favourite info, such as making the favorites appear at the top of the list on first-open/if no location was searched for, or a tab/toggle to just show favourites.

Keep up the good work!

**Comment by gazhayes** [comment]
Thanks @jeremysherriff!

I'll close this one in favour of #47
